name: build the code

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4
      - name: Checkout eshelpers
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/eshelpers
          path: eshelpers
          ref: develop

      - name: Checkout ralf-utils
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/ralf-utils
          path: ralf-utils
          ref: develop


      - name: Install Dependencies
        run: |
          set -x
          sudo apt-get update -y
          sudo apt install -y  libarchive-dev libxml2-dev openssl-dev lz4-dev cmake g++ build-essential

      - name: Build ralf-utils
        run: |
          mkdir ralf-utils/build
          cd ralf-utils/build
          cmake ..
          make

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_INCLUDEDIR=.  -DCMAKE_CXX_STANDARD=17  -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=" -g -std=c++17 -I${GITHUB_WORKSPACE}/eshelpers/packager -I${GITHUB_WORKSPACE}/ralf-utils/include" ..
          make

